#!/usr/bin/env python3
"""Prepend Kimi's DONE handoff entry to docs/KIMI-HANDOFF.md (repo protocol: newest at top)."""
from pathlib import Path

p = Path("/root/ref/sherpacarta/docs/KIMI-HANDOFF.md")
text = p.read_text(encoding="utf-8")

entry = """## 2026-08-11 — Kimi/THOR: 2-min SherpaCarta film via HyperFrames (DONE ✅)

**Delivered:** `video/sherpacarta-2min/final.mp4` — ~2:00, 16:9, 30fps, 1920×1080. Cinematic constitutional documentary, dark forest + emerald + gold. International-first framing; Canada = "live national offering" (scene 17 only). Full VO from `docs/VIDEO-HERMES-HYPERFRAMES.md`, narrated (Kokoro af_nova @ 0.7× → 120.6s), synced captions (whisper.cpp word-level), overlays (grain/vignette/brand).

**Build proof (all pass):** lint 0 errors · validate WCAG AA (12 elements) · inspect 0 errors/0 warnings · draft.mp4 rendered + 20-frame visual check (no blanks, no cut-off, palette on-brand). final.mp4 = high quality.

**How to re-render:** `cd video/sherpacarta-2min && export HYPERFRAMES_PYTHON=/opt/hf-venv/bin/python && npx hyperframes render --quality high --fps 30 --output final.mp4`. Scenes generated by `scripts/gen_scenes_part1.py` + `gen_scenes_part2.py`; captions by `scripts/gen_captions.py` from `transcript.json`.

**Truth rules honored:** no fake metrics · pending ≠ BTC confirmed (stamp card says PENDING · VERIFY ON CHAIN) · movement not corporation · no "127 countries" claims.

**Open for Grok/Cam:** optionally post final.mp4 to sherpacarta.org / socials; 9:16 crop for Stories possible from same composition (not done).

---

"""

p.write_text(entry + text, encoding="utf-8")
print("prepended OK — new size:", p.stat().st_size)
